[template]
src = "prometheus.yml.tmpl"
dest = "/etc/prometheus/prometheus.yml"
keys = [
  "/hosts",
  "/services",
  "/self/container/primary_ip",
  "/self/service/metadata",
]
reload_cmd = "curl -s -X POST prometheus:9090/-/reload"
